// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalaryApp.Data;

namespace SalaryApp.Migrations
{
    [DbContext(typeof(SalaryAppContext))]
    [Migration("20200522083428_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SalaryApp.Models.Allowance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SalaryId")
                        .HasColumnType("int");

                    b.Property<int>("bonusKPI")
                        .HasColumnType("int");

                    b.Property<int>("lunchCharge")
                        .HasColumnType("int");

                    b.Property<int>("phoneCharge")
                        .HasColumnType("int");

                    b.Property<int>("uniformsCharge")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalaryId");

                    b.ToTable("Allowance");
                });

            modelBuilder.Entity("SalaryApp.Models.Overtime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SalaryId")
                        .HasColumnType("int");

                    b.Property<int>("dayOff")
                        .HasColumnType("int");

                    b.Property<int>("overtimeHours")
                        .HasColumnType("int");

                    b.Property<int>("overtimeSalary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalaryId");

                    b.ToTable("Overtime");
                });

            modelBuilder.Entity("SalaryApp.Models.Salary", b =>
                {
                    b.Property<int>("SalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("basicSalary")
                        .HasColumnType("int");

                    b.Property<int>("chargeInsurrance")
                        .HasColumnType("int");

                    b.Property<int>("chargeTax")
                        .HasColumnType("int");

                    b.Property<DateTime>("dayTakeId")
                        .HasColumnType("datetime2");

                    b.Property<int>("keepSalary")
                        .HasColumnType("int");

                    b.Property<int>("staffID")
                        .HasColumnType("int");

                    b.Property<int>("supportCash")
                        .HasColumnType("int");

                    b.Property<int>("totalSalary")
                        .HasColumnType("int");

                    b.HasKey("SalaryId");

                    b.HasIndex("staffID");

                    b.ToTable("Salary");
                });

            modelBuilder.Entity("SalaryApp.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Regency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dayIn")
                        .HasColumnType("datetime2");

                    b.HasKey("StaffId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("SalaryApp.Models.Allowance", b =>
                {
                    b.HasOne("SalaryApp.Models.Salary", "Salary")
                        .WithMany("Allowances")
                        .HasForeignKey("SalaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SalaryApp.Models.Overtime", b =>
                {
                    b.HasOne("SalaryApp.Models.Salary", "Salary")
                        .WithMany("Overtimes")
                        .HasForeignKey("SalaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SalaryApp.Models.Salary", b =>
                {
                    b.HasOne("SalaryApp.Models.Staff", "Staff")
                        .WithMany("Salaries")
                        .HasForeignKey("staffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
